[build]
  publish = "dist"

[context.staging]
  command = "mkdir dist && cp ./staging_redirects ./dist/_redirects"

[context.production]
  command = "mkdir dist && cp ./prod_redirects ./dist/_redirects"