[[redirects]]
from = "/novus-chat/*"
to = "https://embedded-novus.s3.amazonaws.com/:splat"
status = 200
force = true

[[headers]]
  for = "/novus-chat/index.js"
  [headers.values]
    access-control-allow-origin = "*"